image: docker:17.05.0-ce-git

variables:
  GIT_SSL_NO_VERIFY: "true"

before_script:
  - >
    echo "find corresponding branch"
    echo "set status pending"

after_script:
  - >
    echo "find corresponding branch"
    echo "get gitlab pipeline status"
    echo "set final status"

stages:
  - build

build_job:
  stage: build
  script: |
    apk update
    apk add make bash
    make NOCACHE=true docker-build
    make test-docker
    docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    make docker-push IMAGE_NAME="${DOCKER_USERNAME}/fileupload-webapp:${CI_COMMIT_SHA:0:10}"
  tags:
    - j4c

build_job_2:
  stage: build
  script: |
    echo "a dummy 2nd build job"
  tags:
    - j4c